name: Deploy Homologação (beta.meuauralis.com) 🧪

on:
  push:
    branches:
      - beta 

jobs:
  web-deploy:
    name: 🎉 Deploy Beta
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando o código
        uses: actions/checkout@v4

      - name: 🏷️ Gerar Carimbo de Versão (BETA)
        run: echo "Versão Beta - $(git rev-parse --short HEAD)" > version.txt

      - name: 📂 Sincronizando com HostGator (BETA)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_BETA }} 
          password: ${{ secrets.FTP_PASSWORD_BETA }} 
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .php-cs-fixer.php