name: Deploy Produção (meuauralis.com) 🚀

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando o código
        uses: actions/checkout@v4

      - name: 🏷️ Gerar Carimbo de Versão (PRODUÇÃO)
        run: echo "Versão 1.1.${{ github.run_number }}" > version.txt

      - name: 📂 Sincronizando com HostGator (PRODUÇÃO)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }} 
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .php-cs-fixer.php